//! Excellon drill file export for PCB manufacturing.
//!
//! This module provides functionality for generating Excellon (NC drill) files
//! that specify drill hole locations and sizes for through-hole components and vias.
//!
//! # Format
//!
//! Excellon files specify:
//! - Tool definitions (drill diameters)
//! - Drill hit coordinates
//! - Plated vs non-plated hole separation (PTH/NPTH)
//!
//! # Example
//!
//! ```text
//! M48                          ; Start of header
//! ; DRILL file generated by CodeYourPCB
//! METRIC,TZ                    ; Metric units, trailing zero suppression
//! T1C0.3000                    ; Tool 1 = 0.3mm
//! T2C0.8000                    ; Tool 2 = 0.8mm
//! %                            ; End of header
//! T1                           ; Select tool 1
//! X50.800Y30.480               ; Drill hit coordinates
//! X55.880Y30.480
//! T2                           ; Select tool 2
//! X63.500Y50.800
//! M30                          ; End of file
//! ```

pub mod tools;
// pub mod writer; // TODO: Implement writer module

pub use tools::{ToolTable, VIA_DRILL_DEFAULT, THT_DRILL_SMALL, THT_DRILL_LARGE};
// pub use writer::{export_excellon, DrillType}; // TODO: Implement writer module
