//! Excellon drill file writer.
//!
//! Generates complete Excellon drill files with header, tool definitions, and drill hits.

use std::collections::HashMap;

use cypcb_core::{Nm, Point};
use cypcb_world::BoardWorld;
use cypcb_world::footprint::FootprintLibrary;
use cypcb_world::components::{Position, FootprintRef, Rotation};
use cypcb_world::components::trace::Via;

use crate::coords::{CoordinateFormat, nm_to_gerber};
use crate::gerber::copper::ExportError;

use super::tools::ToolTable;

/// Type of drill hole (plated or non-plated).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DrillType {
    /// Plated through-hole (component pads, vias).
    Plated,
    /// Non-plated through-hole (mounting holes).
    NonPlated,
}

/// A single drill hit location.
#[derive(Debug, Clone)]
struct DrillHit {
    position: Point,
    drill_diameter: Nm,
    drill_type: DrillType,
}

/// Export Excellon drill file with optional drill type filtering.
///
/// Generates a complete Excellon drill file with header, tool definitions,
/// and drill hit coordinates. Can filter to only plated (PTH) or non-plated (NPTH) holes.
///
/// # Arguments
///
/// * `world` - Board world with components and vias
/// * `library` - Footprint library for pad definitions
/// * `format` - Coordinate format (typically FORMAT_MM_2_6)
/// * `drill_type_filter` - Optional filter (None = all drills, Some(Plated) = PTH only, Some(NonPlated) = NPTH only)
///
/// # Returns
///
/// Returns the Excellon drill file content as a string.
///
/// # Errors
///
/// Returns `ExportError::FootprintNotFound` if a component references an unknown footprint.
///
/// # Examples
///
/// ```no_run
/// use cypcb_export::excellon::{export_excellon, DrillType};
/// use cypcb_export::coords::CoordinateFormat;
/// use cypcb_world::{BoardWorld, FootprintLibrary};
///
/// let mut world = BoardWorld::new();
/// let library = FootprintLibrary::new();
/// let format = CoordinateFormat::FORMAT_MM_2_6;
///
/// // Export all drills
/// let all = export_excellon(&mut world, &library, &format, None).unwrap();
///
/// // Export only plated holes (PTH)
/// let pth = export_excellon(&mut world, &library, &format, Some(DrillType::Plated)).unwrap();
///
/// // Export only non-plated holes (NPTH)
/// let npth = export_excellon(&mut world, &library, &format, Some(DrillType::NonPlated)).unwrap();
/// ```
pub fn export_excellon(
    world: &mut BoardWorld,
    library: &FootprintLibrary,
    format: &CoordinateFormat,
    drill_type_filter: Option<DrillType>,
) -> Result<String, ExportError> {
    // Collect all drill hits
    let all_hits = collect_drill_hits(world, library)?;

    // Filter by drill type if requested
    let hits: Vec<&DrillHit> = if let Some(filter_type) = drill_type_filter {
        all_hits.iter().filter(|h| h.drill_type == filter_type).collect()
    } else {
        all_hits.iter().collect()
    };

    // Early return if no drills after filtering
    if hits.is_empty() {
        return Ok(generate_empty_excellon(drill_type_filter));
    }

    let mut output = String::new();
    let mut tool_table = ToolTable::new();

    // Assign tool numbers to all unique drill sizes
    for hit in &hits {
        tool_table.get_or_create(hit.drill_diameter);
    }

    // Write header
    output.push_str("M48\n"); // Start of header
    output.push_str("; DRILL file generated by CodeYourPCB\n");

    // Add drill type to header comment
    match drill_type_filter {
        Some(DrillType::Plated) => output.push_str("; Plated Through Holes\n"),
        Some(DrillType::NonPlated) => output.push_str("; Non-Plated Through Holes\n"),
        None => output.push_str("; All drill holes\n"),
    }

    output.push_str("; FORMAT={2:4/ absolute / metric / suppress trailing zeros}\n");
    output.push_str("METRIC,TZ\n"); // Metric units, trailing zero suppression

    // Write tool definitions
    output.push_str(&tool_table.to_header(format));
    output.push_str("\n");

    output.push_str("%\n"); // End of header

    // Group hits by drill size (tool number)
    let grouped_hits = group_hits_by_tool_refs(&hits, &mut tool_table);

    // Output drill hits grouped by tool
    for (tool_num, tool_hits) in grouped_hits {
        output.push_str(&format!("T{}\n", tool_num));
        for hit in tool_hits {
            let x = nm_to_gerber(hit.position.x.0, format);
            let y = nm_to_gerber(hit.position.y.0, format);
            output.push_str(&format!("X{}Y{}\n", x, y));
        }
    }

    // End of file
    output.push_str("M30\n");

    Ok(output)
}

/// Generate empty Excellon file (no drill hits).
fn generate_empty_excellon(drill_type_filter: Option<DrillType>) -> String {
    let mut output = String::new();
    output.push_str("M48\n");
    output.push_str("; DRILL file generated by CodeYourPCB\n");

    match drill_type_filter {
        Some(DrillType::Plated) => output.push_str("; No plated drill holes\n"),
        Some(DrillType::NonPlated) => output.push_str("; No non-plated drill holes\n"),
        None => output.push_str("; No drill holes\n"),
    }

    output.push_str("METRIC,TZ\n");
    output.push_str("%\n");
    output.push_str("M30\n");
    output
}

/// Collect all drill hits from components and vias.
fn collect_drill_hits(
    world: &mut BoardWorld,
    library: &FootprintLibrary,
) -> Result<Vec<DrillHit>, ExportError> {
    let mut hits = Vec::new();

    // Collect from component pads (through-hole)
    let mut query = world.ecs_mut().query::<(&Position, &FootprintRef, &Rotation)>();

    for (position, footprint_ref, rotation) in query.iter(world.ecs()) {
        // Look up footprint in library
        let footprint = library.get(&footprint_ref.0)
            .ok_or_else(|| ExportError::FootprintNotFound(footprint_ref.0.clone()))?;

        // Iterate over pads with drill holes
        for pad in &footprint.pads {
            if let Some(drill_diameter) = pad.drill {
                // Calculate absolute position (component position + rotated pad offset)
                let abs_pos = calculate_pad_position(position.0, pad.position, rotation.0);

                hits.push(DrillHit {
                    position: abs_pos,
                    drill_diameter,
                    drill_type: DrillType::Plated, // Component pads are always plated
                });
            }
        }
    }

    // Collect from vias
    let mut via_query = world.ecs_mut().query::<&Via>();
    for via in via_query.iter(world.ecs()) {
        hits.push(DrillHit {
            position: via.position,
            drill_diameter: via.drill,
            drill_type: DrillType::Plated, // Vias are always plated
        });
    }

    Ok(hits)
}

/// Group drill hits by tool number.
///
/// Returns a Vec of (tool_number, hits) sorted by tool number.
fn group_hits_by_tool<'a>(hits: &'a [DrillHit], tool_table: &mut ToolTable) -> Vec<(u8, Vec<&'a DrillHit>)> {
    let mut grouped: HashMap<u8, Vec<&'a DrillHit>> = HashMap::new();

    for hit in hits {
        let tool_num = tool_table.get_or_create(hit.drill_diameter);
        grouped.entry(tool_num).or_default().push(hit);
    }

    // Sort by tool number
    let mut result: Vec<_> = grouped.into_iter().collect();
    result.sort_by_key(|(tool_num, _)| *tool_num);

    result
}

/// Group drill hit references by tool number.
///
/// This variant takes references to DrillHits (used when filtering).
fn group_hits_by_tool_refs<'a>(hits: &[&'a DrillHit], tool_table: &mut ToolTable) -> Vec<(u8, Vec<&'a DrillHit>)> {
    let mut grouped: HashMap<u8, Vec<&'a DrillHit>> = HashMap::new();

    for hit in hits {
        let tool_num = tool_table.get_or_create(hit.drill_diameter);
        grouped.entry(tool_num).or_default().push(hit);
    }

    // Sort by tool number
    let mut result: Vec<_> = grouped.into_iter().collect();
    result.sort_by_key(|(tool_num, _)| *tool_num);

    result
}

/// Calculate absolute pad position from component position, pad offset, and rotation.
///
/// This is the same calculation used in copper export. Rotation is applied to the
/// pad offset, then added to the component position.
///
/// # Arguments
///
/// * `component_pos` - Component center position
/// * `pad_offset` - Pad position relative to component center
/// * `rotation_millideg` - Component rotation in millidegrees (0-359999)
pub(crate) fn calculate_pad_position(component_pos: Point, pad_offset: Point, rotation_millideg: i32) -> Point {
    if rotation_millideg == 0 {
        // No rotation: simple addition
        Point::new(
            Nm(component_pos.x.0 + pad_offset.x.0),
            Nm(component_pos.y.0 + pad_offset.y.0),
        )
    } else {
        // Convert rotation to radians
        let angle_rad = (rotation_millideg as f64) / 1000.0 * std::f64::consts::PI / 180.0;
        let cos = angle_rad.cos();
        let sin = angle_rad.sin();

        // Rotate pad offset around origin
        let rotated_x = pad_offset.x.0 as f64 * cos - pad_offset.y.0 as f64 * sin;
        let rotated_y = pad_offset.x.0 as f64 * sin + pad_offset.y.0 as f64 * cos;

        // Add to component position
        Point::new(
            Nm(component_pos.x.0 + rotated_x.round() as i64),
            Nm(component_pos.y.0 + rotated_y.round() as i64),
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use cypcb_world::BoardWorld;
    use cypcb_world::footprint::FootprintLibrary;

    #[test]
    fn test_export_empty_board() {
        let mut world = BoardWorld::new();
        let library = FootprintLibrary::new();
        let format = CoordinateFormat::FORMAT_MM_2_6;

        let result = export_excellon(&mut world, &library, &format, None).unwrap();

        assert!(result.contains("M48"));
        assert!(result.contains("No drill holes"));
        assert!(result.contains("M30"));
    }

    #[test]
    fn test_export_header_format() {
        let mut world = BoardWorld::new();
        let library = FootprintLibrary::new();
        let format = CoordinateFormat::FORMAT_MM_2_6;

        let result = export_excellon(&mut world, &library, &format, None).unwrap();

        assert!(result.contains("M48")); // Start of header
        assert!(result.contains("METRIC,TZ")); // Metric units
        assert!(result.contains("%")); // End of header
        assert!(result.contains("M30")); // End of file
    }

    #[test]
    fn test_calculate_pad_position_no_rotation() {
        let comp_pos = Point::from_mm(10.0, 20.0);
        let pad_offset = Point::from_mm(1.0, 2.0);

        let result = calculate_pad_position(comp_pos, pad_offset, 0);

        assert_eq!(result, Point::from_mm(11.0, 22.0));
    }

    #[test]
    fn test_calculate_pad_position_with_rotation() {
        let comp_pos = Point::from_mm(10.0, 10.0);
        let pad_offset = Point::from_mm(1.0, 0.0);

        // 90 degree rotation (90,000 millidegrees)
        let result = calculate_pad_position(comp_pos, pad_offset, 90_000);

        // Pad at (1, 0) rotated 90 degrees becomes (0, 1)
        // Component at (10, 10), so result should be (10, 11)
        assert_eq!(result.x, Nm::from_mm(10.0));
        // Allow small floating-point error
        assert!((result.y.0 - Nm::from_mm(11.0).0).abs() < 1000); // Within 1µm
    }

    #[test]
    fn test_collect_drill_hits_empty() {
        let mut world = BoardWorld::new();
        let library = FootprintLibrary::new();

        let hits = collect_drill_hits(&mut world, &library).unwrap();

        assert_eq!(hits.len(), 0);
    }

    #[test]
    fn test_group_hits_by_tool_empty() {
        let hits = vec![];
        let mut tool_table = ToolTable::new();

        let grouped = group_hits_by_tool(&hits, &mut tool_table);

        assert_eq!(grouped.len(), 0);
    }

    #[test]
    fn test_group_hits_by_tool_single_size() {
        let hits = vec![
            DrillHit {
                position: Point::from_mm(0.0, 0.0),
                drill_diameter: Nm::from_mm(0.3),
                drill_type: DrillType::Plated,
            },
            DrillHit {
                position: Point::from_mm(1.0, 1.0),
                drill_diameter: Nm::from_mm(0.3),
                drill_type: DrillType::Plated,
            },
        ];
        let mut tool_table = ToolTable::new();

        let grouped = group_hits_by_tool(&hits, &mut tool_table);

        assert_eq!(grouped.len(), 1);
        assert_eq!(grouped[0].0, 1); // Tool T1
        assert_eq!(grouped[0].1.len(), 2); // Two hits
    }

    #[test]
    fn test_group_hits_by_tool_multiple_sizes() {
        let hits = vec![
            DrillHit {
                position: Point::from_mm(0.0, 0.0),
                drill_diameter: Nm::from_mm(0.3),
                drill_type: DrillType::Plated,
            },
            DrillHit {
                position: Point::from_mm(1.0, 1.0),
                drill_diameter: Nm::from_mm(0.8),
                drill_type: DrillType::Plated,
            },
            DrillHit {
                position: Point::from_mm(2.0, 2.0),
                drill_diameter: Nm::from_mm(0.3),
                drill_type: DrillType::Plated,
            },
        ];
        let mut tool_table = ToolTable::new();

        let grouped = group_hits_by_tool(&hits, &mut tool_table);

        assert_eq!(grouped.len(), 2);

        // Tool 1 should have 2 hits (0.3mm)
        let tool1 = grouped.iter().find(|(t, _)| *t == 1).unwrap();
        assert_eq!(tool1.1.len(), 2);

        // Tool 2 should have 1 hit (0.8mm)
        let tool2 = grouped.iter().find(|(t, _)| *t == 2).unwrap();
        assert_eq!(tool2.1.len(), 1);
    }

    #[test]
    fn test_export_filter_pth_only() {
        let mut world = BoardWorld::new();
        let library = FootprintLibrary::new();
        let format = CoordinateFormat::FORMAT_MM_2_6;

        let result = export_excellon(&mut world, &library, &format, Some(DrillType::Plated)).unwrap();

        assert!(result.contains("M48"));
        // Empty case says "No plated drill holes"
        assert!(result.contains("plated drill holes"));
        assert!(result.contains("M30"));
    }

    #[test]
    fn test_export_filter_npth_only() {
        let mut world = BoardWorld::new();
        let library = FootprintLibrary::new();
        let format = CoordinateFormat::FORMAT_MM_2_6;

        let result = export_excellon(&mut world, &library, &format, Some(DrillType::NonPlated)).unwrap();

        assert!(result.contains("M48"));
        // Empty case says "No non-plated drill holes"
        assert!(result.contains("non-plated drill holes"));
        assert!(result.contains("M30"));
    }

    #[test]
    fn test_export_all_drills() {
        let mut world = BoardWorld::new();
        let library = FootprintLibrary::new();
        let format = CoordinateFormat::FORMAT_MM_2_6;

        let result = export_excellon(&mut world, &library, &format, None).unwrap();

        assert!(result.contains("M48"));
        // Empty case says "No drill holes"
        assert!(result.contains("drill holes"));
        assert!(result.contains("M30"));
    }
}
