//! CodeYourPCB Parser
//!
//! Tree-sitter based parser for the CodeYourPCB DSL.
//! Provides incremental parsing with error recovery.
//!
//! # Overview
//!
//! This crate provides:
//! - Tree-sitter grammar bindings for the CodeYourPCB DSL
//! - AST (Abstract Syntax Tree) type definitions
//! - Tree-sitter CST to typed AST conversion
//! - Rich error reporting with miette integration
//!
//! # Grammar
//!
//! The grammar supports the following constructs:
//!
//! ```cypcb
//! version 1
//!
//! board blink {
//!     size 30mm x 20mm
//!     layers 2
//! }
//!
//! component R1 resistor "0402" {
//!     value "330"
//!     at 10mm, 8mm
//! }
//!
//! net VCC {
//!     J1.1
//!     R1.1
//! }
//! ```
//!
//! # Quick Start
//!
//! ```rust
//! use cypcb_parser::{parse, CypcbParser};
//!
//! // Convenience function
//! let result = parse("version 1\nboard test { size 10mm x 10mm }");
//! if result.is_ok() {
//!     println!("Parsed {} definitions", result.value.definitions.len());
//! }
//!
//! // Or use the parser struct for multiple parses
//! let mut parser = CypcbParser::new();
//! let result = parser.parse("board another { size 20mm x 20mm }");
//! ```
//!
//! # Low-level Usage
//!
//! For direct access to the Tree-sitter parse tree:
//!
//! ```rust
//! use cypcb_parser::language;
//! use tree_sitter::Parser;
//!
//! let mut parser = Parser::new();
//! parser.set_language(&language()).unwrap();
//!
//! let source = "version 1\nboard test { size 10mm x 10mm }";
//! let tree = parser.parse(source, None).unwrap();
//! println!("{}", tree.root_node().to_sexp());
//! ```

pub mod ast;
pub mod errors;
pub mod parser;

use tree_sitter::Language;

// Re-export key types for convenience
pub use ast::{
    BoardDef, ComponentDef, ComponentKind, Definition, Dimension, Identifier, NetDef, PinId,
    PinRef, PositionExpr, SizeProperty, SourceFile, Span, StringLit,
};
pub use errors::{ParseError, ParseResult};
pub use parser::{parse, CypcbParser};

// Link to the compiled Tree-sitter grammar
extern "C" {
    fn tree_sitter_cypcb() -> Language;
}

/// Returns the Tree-sitter language for CodeYourPCB DSL.
///
/// This language can be used with a `tree_sitter::Parser` for parsing
/// `.cypcb` source files.
///
/// # Safety
///
/// This function is safe because it only calls the generated Tree-sitter
/// language function, which returns a static language definition.
pub fn language() -> Language {
    unsafe { tree_sitter_cypcb() }
}

/// Node kind constants for the grammar.
///
/// These match the node types generated by Tree-sitter and can be used
/// for efficient node type checking without string comparisons.
pub mod node_kinds {
    pub const SOURCE_FILE: &str = "source_file";
    pub const VERSION_STATEMENT: &str = "version_statement";
    pub const BOARD_DEFINITION: &str = "board_definition";
    pub const COMPONENT_DEFINITION: &str = "component_definition";
    pub const NET_DEFINITION: &str = "net_definition";
    pub const SIZE_PROPERTY: &str = "size_property";
    pub const LAYERS_PROPERTY: &str = "layers_property";
    pub const VALUE_PROPERTY: &str = "value_property";
    pub const POSITION_PROPERTY: &str = "position_property";
    pub const ROTATION_PROPERTY: &str = "rotation_property";
    pub const PIN_REF: &str = "pin_ref";
    pub const DIMENSION: &str = "dimension";
    pub const IDENTIFIER: &str = "identifier";
    pub const NUMBER: &str = "number";
    pub const STRING: &str = "string";
    pub const ERROR: &str = "ERROR";
}

#[cfg(test)]
mod tests {
    use super::*;
    use tree_sitter::Parser;

    fn parse(source: &str) -> tree_sitter::Tree {
        let mut parser = Parser::new();
        parser.set_language(&language()).expect("Failed to set language");
        parser.parse(source, None).expect("Failed to parse")
    }

    #[test]
    fn test_language_loads() {
        let lang = language();
        // Verify the language loaded and has a reasonable number of node kinds
        // (the exact count may change as grammar evolves)
        assert!(lang.node_kind_count() > 50);
    }

    #[test]
    fn test_parse_version() {
        let tree = parse("version 1");
        let root = tree.root_node();
        assert_eq!(root.kind(), "source_file");
        assert!(!root.has_error());

        let version = root.child(0).unwrap();
        assert_eq!(version.kind(), "version_statement");
    }

    #[test]
    fn test_parse_board() {
        let tree = parse(
            r#"
            board test {
                size 30mm x 20mm
                layers 2
            }
            "#,
        );
        let root = tree.root_node();
        assert!(!root.has_error());

        let board = root.child(0).unwrap();
        assert_eq!(board.kind(), "board_definition");
    }

    #[test]
    fn test_parse_component() {
        let tree = parse(
            r#"
            component R1 resistor "0402" {
                value "330"
                at 10mm, 8mm
                rotate 90
            }
            "#,
        );
        let root = tree.root_node();
        assert!(!root.has_error());

        let component = root.child(0).unwrap();
        assert_eq!(component.kind(), "component_definition");
    }

    #[test]
    fn test_parse_net() {
        let tree = parse(
            r#"
            net VCC {
                J1.1
                R1.1
                U1.VCC
            }
            "#,
        );
        let root = tree.root_node();
        assert!(!root.has_error());

        let net = root.child(0).unwrap();
        assert_eq!(net.kind(), "net_definition");
    }

    #[test]
    fn test_parse_complete_example() {
        let tree = parse(
            r#"
            // LED blink circuit
            version 1

            board blink {
                size 30mm x 20mm
                layers 2
            }

            component R1 resistor "0402" {
                value "330"
                at 10mm, 8mm
            }

            component LED1 led "0603" {
                at 15mm, 8mm
            }

            component J1 connector "pin_header_1x2" {
                at 5mm, 8mm
            }

            net VCC {
                J1.1
                R1.1
            }

            net GND {
                J1.2
                LED1.cathode
            }

            net LED_SIGNAL {
                R1.2
                LED1.anode
            }
            "#,
        );
        let root = tree.root_node();
        assert!(!root.has_error(), "Parse errors: {}", root.to_sexp());
    }

    #[test]
    fn test_error_recovery() {
        // Intentional syntax error: missing closing brace
        let tree = parse("board test { size 10mm x 10mm");
        let root = tree.root_node();
        // Tree-sitter should recover and still produce a tree
        assert!(root.has_error());
        assert_eq!(root.kind(), "source_file");
    }

    #[test]
    fn test_comments() {
        let tree = parse(
            r#"
            // Line comment
            version 1
            /* Block
               comment */
            board test {
                size 10mm x 10mm // inline comment
            }
            "#,
        );
        let root = tree.root_node();
        assert!(!root.has_error());
    }
}
