//! CodeYourPCB Parser
//!
//! Reads the CodeYourPCB DSL into a typed AST.
//!
//! # Overview
//!
//! This crate provides:
//! - the AST every other crate works on
//! - a reader written in Rust, which is what `parse` is
//! - the tree-sitter grammar and its generated C parser, behind a feature, as
//!   the thing the reader is checked against
//! - rich error reporting with miette integration
//!
//! # Feature Flags
//!
//! - `rust-parser` (default): the reader. No C, so it compiles for
//!   `wasm32-unknown-unknown` and the browser engine parses with it.
//! - `tree-sitter-parser`: the grammar and its generated C parser, exported as
//!   `tree_sitter_parse`. `tests/differential.rs` reads every example both
//!   ways and compares the ASTs; `tests/error_parity.rs` checks they reject
//!   the same files. Why there is one reader rather than two, and what the
//!   other one cost, is in `docs/one-parser.md`.
//!
//! # Grammar
//!
//! The grammar supports the following constructs:
//!
//! ```cypcb
//! version 1
//!
//! board blink {
//!     size 30mm x 20mm
//!     layers 2
//! }
//!
//! component R1 resistor "0402" {
//!     value "330"
//!     at 10mm, 8mm
//! }
//!
//! net VCC {
//!     J1.1
//!     R1.1
//! }
//! ```
//!
//! # Quick Start
//!
//! ```rust
//! use cypcb_parser::parse;
//!
//! let result = parse("version 1\nboard test { size 10mm x 10mm }");
//! if result.is_ok() {
//!     println!("Parsed {} definitions", result.value.definitions.len());
//! }
//! ```
//!
//! Errors are collected rather than fatal, so a file with one bad line still
//! returns the rest of the board:
//!
//! ```rust
//! use cypcb_parser::parse;
//!
//! let result = parse("version 1\nfrobnicate 3\n");
//! assert!(!result.errors.is_empty());
//! ```

pub mod ast;
// thiserror/miette derive macros consume enum variant fields via #[error],
// #[source_code], and #[label] attributes, but rustc's unused_assignments lint
// can't see through the macro expansion and false-positives on every field.
#[allow(unused_assignments)]
pub mod errors;

/// Resolving `import` statements against the filesystem.
///
/// Works on the AST, so it needs whichever reader this build has rather than a
/// particular one.
#[cfg(feature = "rust-parser")]
pub mod imports;

// Tree-sitter parser module only available with the feature
#[cfg(feature = "tree-sitter-parser")]
pub mod parser;

/// Tokens for the Rust reader.
#[cfg(feature = "rust-parser")]
pub mod lexer;

/// The Rust reader: `.cypcb` to AST with no C behind it.
///
/// This is what `parse` is, in every build that has it. The tree-sitter parser
/// is kept behind `tree-sitter-parser` as `tree_sitter_parse`, which is what
/// `tests/differential.rs` checks this one against.
#[cfg(feature = "rust-parser")]
pub mod reader;

#[cfg(feature = "tree-sitter-parser")]
use tree_sitter::Language;

// Re-export AST types (always available)
pub use ast::{
    BoardDef, ComponentDef, ComponentKind, Definition, Dimension, Identifier, NetDef, PinId,
    PinRef, PositionExpr, SizeProperty, SourceFile, Span, StringLit, TraceDef, TraceDirective,
    TracePath, TraceVia,
};

// Re-export error types (always available)
pub use errors::{ParseError, ParseResult};
#[cfg(feature = "rust-parser")]
pub use imports::{resolve_imports, ImportError};

// The reader the project ships. `parse` is this one wherever it exists.
#[cfg(feature = "rust-parser")]
pub use reader::read as parse;

// The parser being replaced, under a name of its own so both can be called in
// the same test. See `docs/one-parser.md`.
#[cfg(feature = "tree-sitter-parser")]
pub use parser::{parse as tree_sitter_parse, CypcbParser};

// When only the tree-sitter parser is built, it is still `parse`.
#[cfg(all(feature = "tree-sitter-parser", not(feature = "rust-parser")))]
pub use parser::parse;

// Link to the compiled Tree-sitter grammar (only with feature)
#[cfg(feature = "tree-sitter-parser")]
extern "C" {
    fn tree_sitter_cypcb() -> Language;
}

/// Returns the Tree-sitter language for CodeYourPCB DSL.
///
/// This language can be used with a `tree_sitter::Parser` for parsing
/// `.cypcb` source files.
///
/// # Safety
///
/// This function is safe because it only calls the generated Tree-sitter
/// language function, which returns a static language definition.
///
/// # Availability
///
/// This function is only available with the `tree-sitter-parser` feature.
#[cfg(feature = "tree-sitter-parser")]
pub fn language() -> Language {
    unsafe { tree_sitter_cypcb() }
}

/// Node kind constants for the grammar.
///
/// These match the node types generated by Tree-sitter and can be used
/// for efficient node type checking without string comparisons.
#[cfg(feature = "tree-sitter-parser")]
pub mod node_kinds {
    pub const SOURCE_FILE: &str = "source_file";
    pub const VERSION_STATEMENT: &str = "version_statement";
    pub const BOARD_DEFINITION: &str = "board_definition";
    pub const COMPONENT_DEFINITION: &str = "component_definition";
    pub const NET_DEFINITION: &str = "net_definition";
    pub const SIZE_PROPERTY: &str = "size_property";
    pub const LAYERS_PROPERTY: &str = "layers_property";
    pub const VALUE_PROPERTY: &str = "value_property";
    pub const POSITION_PROPERTY: &str = "position_property";
    pub const ROTATION_PROPERTY: &str = "rotation_property";
    pub const PIN_REF: &str = "pin_ref";
    pub const DIMENSION: &str = "dimension";
    pub const IDENTIFIER: &str = "identifier";
    pub const NUMBER: &str = "number";
    pub const STRING: &str = "string";
    pub const ERROR: &str = "ERROR";
}

#[cfg(all(test, feature = "tree-sitter-parser"))]
mod tests {
    use super::*;
    use tree_sitter::Parser;

    fn parse(source: &str) -> tree_sitter::Tree {
        let mut parser = Parser::new();
        parser
            .set_language(&language())
            .expect("Failed to set language");
        parser.parse(source, None).expect("Failed to parse")
    }

    #[test]
    fn test_language_loads() {
        let lang = language();
        // Verify the language loaded and has a reasonable number of node kinds
        // (the exact count may change as grammar evolves)
        assert!(lang.node_kind_count() > 50);
    }

    #[test]
    fn test_parse_version() {
        let tree = parse("version 1");
        let root = tree.root_node();
        assert_eq!(root.kind(), "source_file");
        assert!(!root.has_error());

        let version = root.child(0).unwrap();
        assert_eq!(version.kind(), "version_statement");
    }

    #[test]
    fn test_parse_board() {
        let tree = parse(
            r#"
            board test {
                size 30mm x 20mm
                layers 2
            }
            "#,
        );
        let root = tree.root_node();
        assert!(!root.has_error());

        let board = root.child(0).unwrap();
        assert_eq!(board.kind(), "board_definition");
    }

    #[test]
    fn test_parse_component() {
        let tree = parse(
            r#"
            component R1 resistor "0402" {
                value "330"
                at 10mm, 8mm
                rotate 90
            }
            "#,
        );
        let root = tree.root_node();
        assert!(!root.has_error());

        let component = root.child(0).unwrap();
        assert_eq!(component.kind(), "component_definition");
    }

    #[test]
    fn test_parse_net() {
        let tree = parse(
            r#"
            net VCC {
                J1.1
                R1.1
                U1.VCC
            }
            "#,
        );
        let root = tree.root_node();
        assert!(!root.has_error());

        let net = root.child(0).unwrap();
        assert_eq!(net.kind(), "net_definition");
    }

    #[test]
    fn test_parse_complete_example() {
        let tree = parse(
            r#"
            // LED blink circuit
            version 1

            board blink {
                size 30mm x 20mm
                layers 2
            }

            component R1 resistor "0402" {
                value "330"
                at 10mm, 8mm
            }

            component LED1 led "0603" {
                at 15mm, 8mm
            }

            component J1 connector "pin_header_1x2" {
                at 5mm, 8mm
            }

            net VCC {
                J1.1
                R1.1
            }

            net GND {
                J1.2
                LED1.cathode
            }

            net LED_SIGNAL {
                R1.2
                LED1.anode
            }
            "#,
        );
        let root = tree.root_node();
        assert!(!root.has_error(), "Parse errors: {}", root.to_sexp());
    }

    #[test]
    fn test_error_recovery() {
        // Intentional syntax error: missing closing brace
        let tree = parse("board test { size 10mm x 10mm");
        let root = tree.root_node();
        // Tree-sitter should recover and still produce a tree
        assert!(root.has_error());
        assert_eq!(root.kind(), "source_file");
    }

    #[test]
    fn test_comments() {
        let tree = parse(
            r#"
            // Line comment
            version 1
            /* Block
               comment */
            board test {
                size 10mm x 10mm // inline comment
            }
            "#,
        );
        let root = tree.root_node();
        assert!(!root.has_error());
    }

    #[test]
    fn test_parse_footprint_definition() {
        let tree = parse(
            r#"
            footprint MY_PKG {
                description "Custom package"
                pad 1 rect at 0mm, 0mm size 1mm x 0.5mm
                pad 2 rect at 2mm, 0mm size 1mm x 0.5mm
                courtyard 4mm x 2mm
            }
            "#,
        );
        let root = tree.root_node();
        assert!(!root.has_error(), "Parse errors: {}", root.to_sexp());

        let footprint = root.child(0).unwrap();
        assert_eq!(footprint.kind(), "footprint_definition");
    }

    #[test]
    fn test_parse_footprint_with_drill() {
        let tree = parse(
            r#"
            footprint THT_2PIN {
                pad 1 circle at 0mm, 0mm size 1.8mm x 1.8mm drill 1.0mm
                pad 2 circle at 2.54mm, 0mm size 1.8mm x 1.8mm drill 1.0mm
            }
            "#,
        );
        let root = tree.root_node();
        assert!(!root.has_error(), "Parse errors: {}", root.to_sexp());

        let footprint = root.child(0).unwrap();
        assert_eq!(footprint.kind(), "footprint_definition");
    }

    #[test]
    fn test_parse_footprint_all_pad_shapes() {
        let tree = parse(
            r#"
            footprint ALL_SHAPES {
                pad 1 rect at 0mm, 0mm size 1mm x 1mm
                pad 2 circle at 2mm, 0mm size 1mm x 1mm
                pad 3 roundrect at 4mm, 0mm size 1mm x 1mm
                pad 4 oblong at 6mm, 0mm size 1mm x 2mm
            }
            "#,
        );
        let root = tree.root_node();
        assert!(!root.has_error(), "Parse errors: {}", root.to_sexp());
    }
}
