//! Gerber X2 header generation.
//!
//! Generates standard Gerber headers with X2 extended attributes per the
//! Gerber Layer Format specification (revision 2023.03).
//!
//! X2 attributes provide metadata about the file function, creation date,
//! and generating software for better traceability in manufacturing.

use chrono::Utc;
use crate::coords::CoordinateFormat;

/// Copper layer side designation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CopperSide {
    /// Top copper layer
    Top,
    /// Bottom copper layer
    Bottom,
    /// Inner copper layer (numbered 1, 2, 3...)
    Inner(u8),
}

/// Board side for non-copper layers.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Side {
    /// Top side
    Top,
    /// Bottom side
    Bottom,
}

/// Gerber file function enumeration.
///
/// Defines the purpose of this Gerber file in the board stackup.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum GerberFileFunction {
    /// Copper layer (with side and optional layer number)
    Copper(CopperSide, Option<u8>),
    /// Soldermask layer (prevents solder flow except at pads)
    Soldermask(Side),
    /// Silkscreen layer (component designators, logos)
    Silkscreen(Side),
    /// Solderpaste layer (stencil for SMD assembly)
    Solderpaste(Side),
    /// Board profile/outline
    Profile,
    /// Drill file (handled separately, but included for completeness)
    Drill,
}

impl GerberFileFunction {
    /// Convert file function to X2 TF.FileFunction attribute value.
    ///
    /// Per Gerber X2 spec section 5.6.2, the FileFunction attribute
    /// identifies the layer type for CAM systems.
    ///
    /// # Examples
    ///
    /// - Copper(Top, Some(1)) -> "Copper,L1,Top"
    /// - Copper(Bottom, Some(2)) -> "Copper,L2,Bot"
    /// - Soldermask(Top) -> "Soldermask,Top"
    pub fn to_x2_attribute(&self, total_layers: u8) -> String {
        match self {
            GerberFileFunction::Copper(side, layer_num) => {
                let layer_num = layer_num.unwrap_or_else(|| match side {
                    CopperSide::Top => 1,
                    CopperSide::Bottom => total_layers,
                    CopperSide::Inner(n) => n + 1, // L2 for first inner layer
                });
                let side_str = match side {
                    CopperSide::Top => "Top",
                    CopperSide::Bottom => "Bot",
                    CopperSide::Inner(_) => "Inr",
                };
                format!("Copper,L{},{}", layer_num, side_str)
            }
            GerberFileFunction::Soldermask(side) => {
                let side_str = match side {
                    Side::Top => "Top",
                    Side::Bottom => "Bot",
                };
                format!("Soldermask,{}", side_str)
            }
            GerberFileFunction::Silkscreen(side) => {
                let side_str = match side {
                    Side::Top => "Top",
                    Side::Bottom => "Bot",
                };
                format!("Legend,{}", side_str)
            }
            GerberFileFunction::Solderpaste(side) => {
                let side_str = match side {
                    Side::Top => "Top",
                    Side::Bottom => "Bot",
                };
                format!("Paste,{}", side_str)
            }
            GerberFileFunction::Profile => "Profile,NP".to_string(),
            GerberFileFunction::Drill => "Plated,1,2,PTH".to_string(),
        }
    }
}

/// Write Gerber X2 header with file attributes.
///
/// Generates a complete Gerber header including:
/// - Generator comment
/// - Coordinate format declaration (%FS)
/// - Unit mode declaration (%MO)
/// - X2 attributes (GenerationSoftware, CreationDate, FileFunction, Part)
///
/// # Arguments
///
/// * `function` - File function (copper layer, mask, etc.)
/// * `board_name` - Name of the board (for reference)
/// * `format` - Coordinate format specification
/// * `total_layers` - Total number of copper layers in stackup
///
/// # Examples
///
/// ```
/// use cypcb_export::gerber::header::{write_header, GerberFileFunction, CopperSide};
/// use cypcb_export::coords::CoordinateFormat;
///
/// let header = write_header(
///     &GerberFileFunction::Copper(CopperSide::Top, Some(1)),
///     "my_board",
///     &CoordinateFormat::FORMAT_MM_2_6,
///     2,
/// );
///
/// assert!(header.contains("TF.FileFunction,Copper,L1,Top"));
/// assert!(header.contains("CodeYourPCB"));
/// ```
pub fn write_header(
    function: &GerberFileFunction,
    board_name: &str,
    format: &CoordinateFormat,
    total_layers: u8,
) -> String {
    let mut header = String::new();

    // Generator comment
    header.push_str(&format!(
        "G04 Gerber file generated by CodeYourPCB*\n"
    ));
    header.push_str(&format!(
        "G04 Board: {}*\n",
        board_name
    ));
    header.push_str("G04 Format: RS-274X (Gerber) with X2 attributes*\n");

    // Coordinate format declaration
    let format_str = crate::coords::gerber_format_string(format);
    header.push_str(&format!("{}\n", format_str));

    // Unit mode declaration
    let unit_str = match format.unit {
        crate::coords::Unit::Millimeters => "MM",
        crate::coords::Unit::Inches => "IN",
    };
    header.push_str(&format!("%MO{}*%\n", unit_str));

    // X2 attributes
    // TF.GenerationSoftware
    let version = env!("CARGO_PKG_VERSION");
    header.push_str(&format!(
        "G04 #@! TF.GenerationSoftware,CodeYourPCB,cypcb,{}*\n",
        version
    ));

    // TF.CreationDate
    let now = Utc::now();
    let iso_date = now.format("%Y-%m-%dT%H:%M:%S%z").to_string();
    header.push_str(&format!(
        "G04 #@! TF.CreationDate,{}*\n",
        iso_date
    ));

    // TF.FileFunction
    let file_function = function.to_x2_attribute(total_layers);
    header.push_str(&format!(
        "G04 #@! TF.FileFunction,{}*\n",
        file_function
    ));

    // TF.Part - assume single board (not panelized)
    header.push_str("G04 #@! TF.Part,Single*\n");

    header
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::coords::CoordinateFormat;

    #[test]
    fn test_copper_top_to_x2_attribute() {
        let func = GerberFileFunction::Copper(CopperSide::Top, Some(1));
        assert_eq!(func.to_x2_attribute(2), "Copper,L1,Top");
    }

    #[test]
    fn test_copper_bottom_to_x2_attribute() {
        let func = GerberFileFunction::Copper(CopperSide::Bottom, Some(2));
        assert_eq!(func.to_x2_attribute(2), "Copper,L2,Bot");
    }

    #[test]
    fn test_copper_inner_to_x2_attribute() {
        let func = GerberFileFunction::Copper(CopperSide::Inner(1), Some(2));
        assert_eq!(func.to_x2_attribute(4), "Copper,L2,Inr");
    }

    #[test]
    fn test_copper_auto_layer_number() {
        // Top without explicit layer number
        let func = GerberFileFunction::Copper(CopperSide::Top, None);
        assert_eq!(func.to_x2_attribute(2), "Copper,L1,Top");

        // Bottom without explicit layer number
        let func = GerberFileFunction::Copper(CopperSide::Bottom, None);
        assert_eq!(func.to_x2_attribute(2), "Copper,L2,Bot");
        assert_eq!(func.to_x2_attribute(4), "Copper,L4,Bot");
    }

    #[test]
    fn test_soldermask_to_x2_attribute() {
        let func = GerberFileFunction::Soldermask(Side::Top);
        assert_eq!(func.to_x2_attribute(2), "Soldermask,Top");

        let func = GerberFileFunction::Soldermask(Side::Bottom);
        assert_eq!(func.to_x2_attribute(2), "Soldermask,Bot");
    }

    #[test]
    fn test_solderpaste_to_x2_attribute() {
        let func = GerberFileFunction::Solderpaste(Side::Top);
        assert_eq!(func.to_x2_attribute(2), "Paste,Top");
    }

    #[test]
    fn test_silkscreen_to_x2_attribute() {
        let func = GerberFileFunction::Silkscreen(Side::Top);
        assert_eq!(func.to_x2_attribute(2), "Legend,Top");
    }

    #[test]
    fn test_profile_to_x2_attribute() {
        let func = GerberFileFunction::Profile;
        assert_eq!(func.to_x2_attribute(2), "Profile,NP");
    }

    #[test]
    fn test_write_header_contains_format() {
        let format = CoordinateFormat::FORMAT_MM_2_6;
        let header = write_header(
            &GerberFileFunction::Copper(CopperSide::Top, Some(1)),
            "test_board",
            &format,
            2,
        );

        assert!(header.contains("%FSLAX26Y26*%"));
        assert!(header.contains("%MOMM*%"));
    }

    #[test]
    fn test_write_header_contains_x2_attributes() {
        let format = CoordinateFormat::FORMAT_MM_2_6;
        let header = write_header(
            &GerberFileFunction::Copper(CopperSide::Top, Some(1)),
            "test_board",
            &format,
            2,
        );

        assert!(header.contains("TF.GenerationSoftware,CodeYourPCB"));
        assert!(header.contains("TF.CreationDate"));
        assert!(header.contains("TF.FileFunction,Copper,L1,Top"));
        assert!(header.contains("TF.Part,Single"));
    }

    #[test]
    fn test_write_header_board_name() {
        let format = CoordinateFormat::FORMAT_MM_2_6;
        let header = write_header(
            &GerberFileFunction::Soldermask(Side::Top),
            "my_awesome_board",
            &format,
            2,
        );

        assert!(header.contains("Board: my_awesome_board"));
    }

    #[test]
    fn test_write_header_inch_format() {
        let format = CoordinateFormat::FORMAT_INCH_2_4;
        let header = write_header(
            &GerberFileFunction::Copper(CopperSide::Bottom, Some(2)),
            "test",
            &format,
            2,
        );

        assert!(header.contains("%FSLAX24Y24*%"));
        assert!(header.contains("%MOIN*%"));
    }
}
