//! Build script for cypcb-parser
//!
//! Compiles the Tree-sitter grammar's generated C parser into a static library.
//! The grammar/src/ directory must be generated before building:
//!   cd grammar && npx tree-sitter generate

fn main() {
    let grammar_dir = std::path::Path::new("grammar");
    let src_dir = grammar_dir.join("src");

    // Rerun if grammar source files change
    println!("cargo:rerun-if-changed=grammar/grammar.js");
    println!("cargo:rerun-if-changed=grammar/src/parser.c");

    let parser_c = src_dir.join("parser.c");

    // Check if parser.c exists (generated by tree-sitter generate)
    if !parser_c.exists() {
        panic!(
            "Tree-sitter parser not generated. Run:\n  \
             cd crates/cypcb-parser/grammar && npm install && npx tree-sitter generate"
        );
    }

    // Compile the Tree-sitter parser
    cc::Build::new()
        .file(&parser_c)
        .include(&src_dir)
        // Suppress common warnings from generated code
        .flag_if_supported("-Wno-unused-parameter")
        .flag_if_supported("-Wno-unused-but-set-variable")
        .flag_if_supported("-Wno-trigraphs")
        // Optimize for size in release builds
        .opt_level(2)
        .compile("tree-sitter-cypcb");

    println!("cargo:rustc-link-lib=static=tree-sitter-cypcb");
}
